[tools]
lefthook = "latest"
node = "24"
"npm:conventional-changelog-cli" = "latest"
pnpm = "10.28.2"

[tasks.changelog]
description = "Generate changelog via git history"
run = [
  "conventional-changelog -i whatschange.md -s -n changelog.json -k plugin.json -c plugin.json",
  "npx prettier -w whatschange.md",
  "git add whatschange.md",
]
